In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print(f"Original temperature readings: {temperature}")

Original temperature readings: [25 28 31 35 38 27 33 40]


### a. Add 2°C to every reading using vectorization.

In [30]:

corrected_temperature = temperature + 2
print(f"Temperature readings after adding 2°C: {corrected_temperature}")

Temperature readings after adding 2°C: [27 30 33 37 40 29 35 42]


### b. Convert all temperatures from Celsius to Fahrenheit.

In [31]:

temperature_fahrenheit = (9/5) * corrected_temperature + 32
print(f"Temperature readings in Fahrenheit: {temperature_fahrenheit}")

Temperature readings in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


### c. Identify all readings greater than 32°C using Boolean indexing.

In [32]:

higher_than_32_celsius_mask = corrected_temperature > 32
readings_greater_than_32c = corrected_temperature[higher_than_32_celsius_mask]
print(f"Readings greater than 32°C: {readings_greater_than_32c}")

Readings greater than 32°C: [33 37 40 35 42]


### d. Count how many readings exceed 32°C.

In [33]:

count_greater_than_32c = np.sum(higher_than_32_celsius_mask)
print(f"Number of readings exceeding 32°C: {count_greater_than_32c}")

Number of readings exceeding 32°C: 5


### e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.

**Vectorization** is the process of performing operations on entire arrays or collections of data at once, rather than iterating through individual elements. In NumPy, this is highly optimized because operations are implemented in C and Fortran, allowing them to leverage CPU-level optimizations (like SIMD instructions). This leads to significantly faster execution times, especially for large datasets, compared to Python's native for loops, which incur overhead for each iteration.

**Boolean indexing** is a powerful feature where you use a Boolean array (an array of True/False values) to select elements from another array. Instead of writing conditional statements within a loop to check each element, Boolean indexing allows you to filter data concisely and efficiently. Like vectorization, it's implemented at a lower level, providing performance benefits over explicit iteration and conditional checks in Python loops. It's also more readable and less prone to off-by-one errors.

## Q2. Operations on a 2D NumPy Array (Steps Data)

In [6]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print(f"Original steps matrix:\n{steps}")

Original steps matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


### a. Calculate the total steps recorded.

In [7]:
total_steps = np.sum(steps)
print(f"Total steps recorded: {total_steps}")

Total steps recorded: 84200


### b. Calculate the mean number of steps.

In [8]:
mean_steps = np.mean(steps)
print(f"Mean number of steps: {mean_steps:.2f}")

Mean number of steps: 7016.67


### c. Find the maximum and minimum values.

In [9]:
max_steps = np.max(steps)
min_steps = np.min(steps)
print(f"Maximum steps recorded: {max_steps}")
print(f"Minimum steps recorded: {min_steps}")

Maximum steps recorded: 9500
Minimum steps recorded: 4500


### d. Calculate the total steps for each day using `axis=0`.

In [10]:
total_steps_per_day = np.sum(steps, axis=0)
print(f"Total steps for each day: {total_steps_per_day}")
print(f"  (Column 0: Day 1, Column 1: Day 2, Column 2: Day 3)")

Total steps for each day: [26500 27300 30400]
  (Column 0: Day 1, Column 1: Day 2, Column 2: Day 3)


### e. Calculate the total steps for each user using `axis=1`.

In [11]:
total_steps_per_user = np.sum(steps, axis=1)
print(f"Total steps for each user: {total_steps_per_user}")
print(f"  (Row 0: User 1, Row 1: User 2, etc.)")

Total steps for each user: [18300 24500 14400 27000]
  (Row 0: User 1, Row 1: User 2, etc.)


### f. Find the user/day position containing the maximum number of steps using `argmax()`.

In [12]:
max_steps_flat_index = np.argmax(steps)
max_steps_2d_coords = np.unravel_index(max_steps_flat_index, steps.shape)

user_index = max_steps_2d_coords[0]
day_index = max_steps_2d_coords[1]

print(f"Position of maximum steps (user, day): {max_steps_2d_coords}")
print(f"This corresponds to User {user_index + 1} on Day {day_index + 1} with {steps[user_index, day_index]} steps.")

Position of maximum steps (user, day): (np.int64(3), np.int64(2))
This corresponds to User 4 on Day 3 with 9500 steps.


## Q3. Advanced NumPy Array Operations

### a. Create the following NumPy array: `original = np.array([1, 2, 3, 4, 5, 6])`

In [13]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])
print(f"Original array: {original}")

Original array: [1 2 3 4 5 6]


### b. Create a slice containing elements from index 1 to 4 and store it in a variable named `subset`.

In [34]:
subset = original[1:5]
print(f"Subset (slice from index 1 to 4): {subset}")

Subset (slice from index 1 to 4): [999   3   4   5]


### c. Modify the first element of `subset` to 999 and display both `original` and `subset`.

In [15]:
subset[0] = 999
print(f"Original array after modifying subset: {original}")
print(f"Subset array after modification: {subset}")
print("Notice how modifying the slice (`subset`) also modified the `original` array. This is because slices in NumPy are views of the original data, not copies.")

Original array after modifying subset: [  1 999   3   4   5   6]
Subset array after modification: [999   3   4   5]
Notice how modifying the slice (`subset`) also modified the `original` array. This is because slices in NumPy are views of the original data, not copies.


### d. Create another slice from `original`, but this time use `.copy()`. Modify its first element to 500 and display `original` and the copied array.

In [16]:
copied_subset = original[1:5].copy()
copied_subset[0] = 500
print(f"Original array after modifying copied_subset: {original}")
print(f"Copied subset array after modification: {copied_subset}")
print("Here, modifying the `copied_subset` does NOT affect the `original` array because `.copy()` creates an independent copy of the data.")

Original array after modifying copied_subset: [  1 999   3   4   5   6]
Copied subset array after modification: [500   3   4   5]
Here, modifying the `copied_subset` does NOT affect the `original` array because `.copy()` creates an independent copy of the data.


### e. Create a NumPy array containing the numbers from 1 to 12 using `np.arange()` and reshape it into a 3 × 4 matrix.

In [17]:
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print(f"3x4 Matrix:\n{matrix_3x4}")

3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:
*   First row
*   Last row
*   Second column
*   Elements from rows 1–2 and columns 2–3

In [35]:

first_row = matrix_3x4[0, :]
print(f"First row: {first_row}")

last_row = matrix_3x4[-1, :]
print(f"Last row: {last_row}")

second_column = matrix_3x4[:, 1]
print(f"Second column: {second_column}")

rows_1_2_cols_2_3 = matrix_3x4[1:3, 2:4]
print(f"Elements from rows 1-2 and columns 2-3:\n{rows_1_2_cols_2_3}")

First row: [99  2  3  4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Elements from rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]


### g. Create a flattened version of the 3 × 4 matrix using both `flatten()` and `ravel()`.

In [19]:
flattened_array = matrix_3x4.flatten()
raveled_array = matrix_3x4.ravel()

print(f"Flattened array (using flatten()): {flattened_array}")
print(f"Raveled array (using ravel()): {raveled_array}")

Flattened array (using flatten()): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled array (using ravel()): [ 1  2  3  4  5  6  7  8  9 10 11 12]


### h. Modify an element in the array returned by `ravel()` and observe whether the original array is affected.

In [20]:
raveled_array[0] = 99
print(f"Original matrix after modifying raveled_array:\n{matrix_3x4}")
print(f"Raveled array after modification: {raveled_array}")
print("Modifying the `raveled_array` affects the `original` matrix because `ravel()` usually returns a view of the original array (unless a copy is explicitly requested).")

Original matrix after modifying raveled_array:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Raveled array after modification: [99  2  3  4  5  6  7  8  9 10 11 12]
Modifying the `raveled_array` affects the `original` matrix because `ravel()` usually returns a view of the original array (unless a copy is explicitly requested).


### i. Modify an element in the array returned by `flatten()` and observe whether the original array is affected.

In [21]:
flattened_array[0] = 55
print(f"Original matrix after modifying flattened_array:\n{matrix_3x4}")
print(f"Flattened array after modification: {flattened_array}")
print("Modifying the `flattened_array` does NOT affect the `original` matrix because `flatten()` always returns a copy.")

Original matrix after modifying flattened_array:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array after modification: [55  2  3  4  5  6  7  8  9 10 11 12]
Modifying the `flattened_array` does NOT affect the `original` matrix because `flatten()` always returns a copy.


### j. Display the `shape`, `ndim`, `size`, and `dtype` of the original 3 × 4 matrix.

In [22]:
print(f"Shape of matrix_3x4: {matrix_3x4.shape}")
print(f"Number of dimensions (ndim) of matrix_3x4: {matrix_3x4.ndim}")
print(f"Size (total elements) of matrix_3x4: {matrix_3x4.size}")
print(f"Data type (dtype) of matrix_3x4: {matrix_3x4.dtype}")

Shape of matrix_3x4: (3, 4)
Number of dimensions (ndim) of matrix_3x4: 2
Size (total elements) of matrix_3x4: 12
Data type (dtype) of matrix_3x4: int64


## Q4. Ordinary Least Squares (OLS) with NumPy

In [36]:
import numpy as np

y = np.array([40, 65, 30, 85])
print(f"Dependent variable (y): {y}")

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
print(f"\nIndependent variables (X):\n{X}")

Dependent variable (y): [40 65 30 85]

Independent variables (X):
[[ 6 70  3]
 [ 5 50  6]
 [ 8 80  2]
 [ 4 30  8]]


### a. Display the shape and dimensions of X.

In [24]:
print(f"Shape of X: {X.shape}")
print(f"Dimensions of X (ndim): {X.ndim}")

Shape of X: (4, 3)
Dimensions of X (ndim): 2


### b. Calculate `X.T` and explain what the transpose represents.

In [25]:
X_transpose = X.T
print(f"X transpose (X.T):\n{X_transpose}")
print("\nExplanation: The transpose of a matrix (X.T) is obtained by flipping the matrix over its diagonal. Rows become columns, and columns become rows. In this context, the original matrix X had rows representing users and columns representing features (sleep hours, activity level, stress level). The transposed matrix X.T now has rows representing the features and columns representing the users. This operation is crucial in linear algebra, especially for matrix multiplication in OLS, to align the dimensions correctly.")

X transpose (X.T):
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

Explanation: The transpose of a matrix (X.T) is obtained by flipping the matrix over its diagonal. Rows become columns, and columns become rows. In this context, the original matrix X had rows representing users and columns representing features (sleep hours, activity level, stress level). The transposed matrix X.T now has rows representing the features and columns representing the users. This operation is crucial in linear algebra, especially for matrix multiplication in OLS, to align the dimensions correctly.


### c. Calculate the matrix product: `X.T @ X`

In [26]:
XT_X = X_transpose @ X
print(f"Matrix product (X.T @ X):\n{XT_X}")

Matrix product (X.T @ X):
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


### d. Calculate the matrix inverse using: `np.linalg.inv()` where appropriate.

In [27]:
XT_X_inverse = np.linalg.inv(XT_X)
print(f"Matrix inverse of (X.T @ X):\n{XT_X_inverse}")

Matrix inverse of (X.T @ X):
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


### e. Implement the Ordinary Least Squares equation: $\beta = (X^T X)^{-1} X^T y$ using NumPy.

In [37]:

XT_y = X_transpose @ y
print(f"Matrix product (X.T @ y): {XT_y}")

beta_coefficients = XT_X_inverse @ XT_y
print(f"\nOLS Beta Coefficients: {beta_coefficients}")

Matrix product (X.T @ y): [ 1145 11000  1250]

OLS Beta Coefficients: [-0.15921454  0.14083853 10.06302242]


### f. Explain what the resulting coefficients represent in the context of the three user features.

**Explanation of Coefficients:**

The beta_coefficients calculated are the estimated parameters for our linear regression model. In the context of the three user features (Sleep hours, Activity level, Stress level) and the predicted Assistance Score, these coefficients represent the following:

*   **beta_coefficients[0] (for Sleep hours):** This coefficient indicates the expected change in the assistance score for every one-unit increase in 'Sleep hours', assuming 'Activity level' and 'Stress level' remain constant. A positive value would suggest that more sleep hours are associated with a higher assistance score, while a negative value would suggest the opposite.

*   **beta_coefficients[1] (for Activity level):** This coefficient indicates the expected change in the assistance score for every one-unit increase in 'Activity level', assuming 'Sleep hours' and 'Stress level' remain constant. For example, a positive value means higher activity is associated with a higher assistance score.

*   **beta_coefficients[2] (for Stress level):** This coefficient indicates the expected change in the assistance score for every one-unit increase in 'Stress level', assuming 'Sleep hours' and 'Activity level' remain constant. A negative value here would typically suggest that higher stress levels are associated with a lower assistance score.

In essence, these coefficients quantify the independent impact of each feature on the assistance score within this linear model.

### g. A new user has: `new_user = np.array([5, 40, 7])`. Use your calculated coefficients to obtain a predicted assistance score.

In [38]:
new_user = np.array([5, 40, 7])
print(f"New user features: {new_user}")


predicted_assistance_score = new_user @ beta_coefficients

print(f"\nPredicted assistance score for the new user: {predicted_assistance_score:.2f}")

New user features: [ 5 40  7]

Predicted assistance score for the new user: 75.28
