## Q.1 Create a NumPy 1D array and perform basic operations

In [18]:

import numpy as np
original_array = np.array([10, 20, 30, 40, 50])
print("Original 1D array:")
print(original_array)

Original 1D array:
[10 20 30 40 50]


### a) Addition of 2 in all elements

In [19]:

array_after_addition = original_array + 2
print("Array after adding 2 to each element:")
print(array_after_addition)

Array after adding 2 to each element:
[12 22 32 42 52]


### b) Multiply 3 with all elements

In [20]:

array_after_multiplication = original_array * 3
print("Array after multiplying each element by 3:")
print(array_after_multiplication)

Array after multiplying each element by 3:
[ 30  60  90 120 150]


### c) Divide every element by 2

In [21]:

array_after_division = original_array / 2
print("Array after dividing each element by 2:")
print(array_after_division)

Array after dividing each element by 2:
[ 5. 10. 15. 20. 25.]


## Q.2 Questions on Basic NumPy Array

### a) Reverse the NumPy array

In [22]:

arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)

reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


### b) Find the most frequent value and their indice(s) in the following arrays

#### i. Array x

In [23]:

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
print("Array x:", x)

unique_elements, counts = np.unique(x, return_counts=True)

most_frequent_index = np.argmax(counts)

most_frequent_value_x = unique_elements[most_frequent_index]
print(f"Most frequent value in x: {most_frequent_value_x}")

indices_x = np.where(x == most_frequent_value_x)[0]
print(f"Indices of the most frequent value in x: {indices_x}")

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]


#### ii. Array y

In [24]:

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("Array y:", y)

unique_elements_y, counts_y = np.unique(y, return_counts=True)

most_frequent_index_y = np.argmax(counts_y)

most_frequent_value_y = unique_elements_y[most_frequent_index_y]
print(f"Most frequent value in y: {most_frequent_value_y}")

indices_y = np.where(y == most_frequent_value_y)[0]
print(f"Indices of the most frequent value in y: {indices_y}")

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of the most frequent value in y: [0 1 2]


## Q.3 Accessing elements in a 2-D NumPy array

In [25]:

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print("Original 2-D array:")
print(arr_2d)

Original 2-D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


### a) Access 1st row, 2nd column

In [26]:

element_1_2 = arr_2d[0, 1]
print(f"Element at 1st row, 2nd column: {element_1_2}")

Element at 1st row, 2nd column: 20


### b) Access 3rd row, 1st column

In [27]:

element_3_1 = arr_2d[2, 0]
print(f"Element at 3rd row, 1st column: {element_3_1}")

Element at 3rd row, 1st column: 70


## Q.4 Create a 1-D NumPy array using `linspace()`, analyze its properties, and explore transposition

In [28]:

my_array = np.linspace(10, 100, 25)

print("1-D NumPy array:\n", my_array)
print(f"\nDimensions of the array (ndim): {my_array.ndim}")
print(f"Shape of the array (shape): {my_array.shape}")
print(f"Total elements in the array (size): {my_array.size}")
print(f"Data type of each element (dtype): {my_array.dtype}")
print(f"Total number of bytes consumed by the array (nbytes): {my_array.nbytes} bytes")

1-D NumPy array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions of the array (ndim): 1
Shape of the array (shape): (25,)
Total elements in the array (size): 25
Data type of each element (dtype): float64
Total number of bytes consumed by the array (nbytes): 200 bytes


### Find the transpose of this array using `reshape()` attribute.

In [29]:

reshaped_array = my_array.reshape(-1, 1)
print("\nReshaped array (column vector):\n", reshaped_array)

transposed_reshaped_array = reshaped_array.T
print("\nTranspose of the reshaped array:\n", transposed_reshaped_array)
print(f"Shape of the transposed reshaped array: {transposed_reshaped_array.shape}")


Reshaped array (column vector):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose of the reshaped array:
 [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Shape of the transposed reshaped array: (1, 25)


### Can we do the same with `T` attribute?

In [30]:

transpose_of_1d_array = my_array.T
print("\nOriginal 1D array:\n", my_array)
print(f"Shape of original 1D array: {my_array.shape}")
print("Transpose of 1D array using .T:\n", transpose_of_1d_array)
print(f"Shape of transposed 1D array using .T: {transpose_of_1d_array.shape}")

print("\nExplanation: For a 1-D array, the transpose operation does not change the array itself, so `my_array.T` returns the original array. Transpose is meaningful for 2-D or higher-dimensional arrays.")


Original 1D array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of original 1D array: (25,)
Transpose of 1D array using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of transposed 1D array using .T: (25,)

Explanation: For a 1-D array, the transpose operation does not change the array itself, so `my_array.T` returns the original array. Transpose is meaningful for 2-D or higher-dimensional arrays.


## Q.5 Create, analyze, reshape, and resize a 2-D NumPy array

In [31]:

ucs420_my_name = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original 2-D array (ucs420_my_name):\n", ucs420_my_name)

Original 2-D array (ucs420_my_name):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


### Compute the mean, median, max, min, unique elements

In [33]:

array_mean = np.mean(ucs420_my_name)
print(f"Mean of the array: {array_mean}")

array_median = np.median(ucs420_my_name)
print(f"Median of the array: {array_median}")

array_max = np.max(ucs420_my_name)
print(f"Maximum element in the array: {array_max}")

array_min = np.min(ucs420_my_name)
print(f"Minimum element in the array: {array_min}")

unique_elements_array = np.unique(ucs420_my_name)
print(f"Unique elements in the array: {unique_elements_array}")

Mean of the array: 43.333333333333336
Median of the array: 37.5
Maximum element in the array: 90
Minimum element in the array: 10
Unique elements in the array: [10 15 20 30 35 40 50 60 70 80 90]


### Reshape the array to four rows and three columns

In [34]:

reshaped_ucs420_my_name = ucs420_my_name.reshape(4, 3)
print("\nReshaped array (reshaped_ucs420_my_name - 4 rows, 3 columns):\n", reshaped_ucs420_my_name)
print(f"Shape of reshaped array: {reshaped_ucs420_my_name.shape}")


Reshaped array (reshaped_ucs420_my_name - 4 rows, 3 columns):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Shape of reshaped array: (4, 3)


### Resize the array to two rows and three columns

In [35]:

resized_ucs420_my_name = np.resize(ucs420_my_name, (2, 3))
print("\nResized array (resized_ucs420_my_name - 2 rows, 3 columns):\n", resized_ucs420_my_name)
print(f"Shape of resized array: {resized_ucs420_my_name.shape}")


Resized array (resized_ucs420_my_name - 2 rows, 3 columns):
 [[10 20 30]
 [40 50 60]]
Shape of resized array: (2, 3)
